name: Build OpenAPI Github Page
on:
  push: 
    tags:
      - "v*"
jobs:
  openapi:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@524765e0d7cdaa25759f922a23c931af00ebf2f6 # v1.1.6
        with:
          output: github-pages
          spec-file: docs/openapi.yaml
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@73e62e651178eeba977de2dc9f4c7645b3d01015 # v2.0.0