name: Jest
on:
  pull_request:
    branches:
      - main
  push: 
    tags:
      - "v*"
jobs:
  jest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Setup Test Environment
        run: cp .github/wrangler.tests.toml ./wrangler.toml
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Jest
        run: npm run test